### ISSUE TITLE
Repetición de lógica cuando se modifica a la persona

### ISSUE THREAD

**Issue by rgonzalezt** [matias-alejandro/TP-Monopoly#2]
Cada vez que modificás la cantidad de dinero de la persona estás repitiendo lógica. Para no hacerlo, creá una función que se encargue de modificar la cantidad de dinero, así después la usas cada vez que la necesites.
Te recomiendo que a partir de ahora, para los TPs y parciales de este paradigma, crees este tipo de funciones desde el principio para no repetir lógica. ¿Hay que hacerlo para cada componente del data? A veces sí, a veces no. Por eso es importante leer todo el enunciado antes.

**Comment by juancuiule** [comment]
Resuelto 💯
